name: Validate DAB
  working-directory: dabProject_r
  run: databricks bundle validate -t dev

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - name: Validate Bundle
        run: databricks bundle validate